### ISSUE TITLE
Selection query language

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#113]
Issue #85 identified that the usefulness of Selection Criteria SEL07 - SEL16 (date related) would be limited unless it was possible to specify a range of dates.

Issue #111 identified that SEL01-SEL04 merely duplicate existing functionality unless it were possible to specify multiple values or refer to values in the parent (or child) of the entities being returned.

A possible syntax for ranges and lists described in #85 would cover the range and multiple values cases above but not parent\child references, which prompts whether the SEL criteria should be replaced by a query language.

Do we introduce lists and ranges now, and keep a more comprehensive query language for the future when clearer use cases emerge? or go straight for a more comprehensive query language.

**Comment by franciscave** [comment]
My gut feeling is that it would be worthwhile to add lists and ranges now. As things stand, we don't have a workable method for searching and selecting entities by their properties. I think that adding lists and ranges would strengthen LCF, even if we know that this may have to be superseded by a full query language at some future date. I remain to be convinced that a full query language would be worth adding.

As for the expression of lists and ranges, I don't have any better suggestions than Matthew's suggestions in #85, i.e. use (a,b) and [a,b] for ranges and {a,b} for lists.

**Comment by franciscave** [comment]
This was discussed at the Technical Panel meeting on 14 May 2020. It was decided that there is no urgent requirement to add a full-feature query language to LCF, and that the features that have been added in LCF v1.2.0 are sufficient for current purposes. It was therefore decided to close this issue for the time being.
