### ISSUE TITLE
Third Party\Patron not present requests

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#116]
RNQ02 and RQN04 (not implemented in REST) allow the clients to indicate third party (patron not present) requests for renewal.

In general this might be useful for other types of request to differentiate between direct patron initiated requests (e.g. from a self issue terminal or mobile device) from third party requests (e.g. a background process which polls loans on a patron's behalf and e-mails\text warnings of items nearing their return dates etc.), and if so would also need to be implemented in REST

**Comment by mdovey** [comment]
Technical panel concluded that this could be handled by logging authentication.

If the transaction is authenticated as the patron then it is a "patron present" request. If this is authenticated as "staff" then it is a patron not present request.

Documentation needs updated to reflect this.

**Comment by franciscave** [comment]
See the note I have proposed to be added to REST web service documentation, under #117.

**Comment by franciscave** [comment]
Note added to specification of REST web service implementation. See pull request #277.
