### ISSUE TITLE
Renew all

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#117]
RNQ01 and RNQ02 in theory permit renew all operations. In theory because Q11D05 is currently described as "Mandatory when renewing or cancelling a check-out or renewal." and it isn't clear what loan should be referred to here in a renew all request.

Moreover, this is not implemented in REST (not least as it would really be an operation on a patron or patrons\id\loans list rather than on a loan).

**Comment by franciscave** [comment]
In the Data Framework both Q11D04 and Q11D05 are specified to be mandatory when renewing a loan. Neither of these is implemented in the REST implementation, and nor is Q11D02, which uses list RNQ. So there is currently an inconsistency between the Data Framework and the REST implementation. In essence, the REST implementation does not implement the circulation function 11 (check-out/renewal) at all, but uses the core functions 03 (create entity) and 04 (modify entity) to achieve the same result.

For renewals, the approach taken currently in the REST implementation is different: a loan is renewed by cancelling the current loan and creating a new loan based upon the current loan. This obviously only works for one loan at a time, and each loan only relates to a single item. Thus "renew all" is not currently possible in the REST implementation, except by retrieving all the current loans for a patron and renewing them one by one, and this approach is not currently documented.

I think I need to understand more about how "renew all" works in practice before making proposals for documentation changes. It's difficult to see how "renew all" could be implemented in a RESTful way without breaking it down into a series of GETs, PUTs, and POSTs.

**Comment by franciscave** [comment]
In the Technical Panel meeting on 28 May it was suggested that the "renew all" option does not need to be implemented in the REST web service implementation of LCF, because the number of items being renewed is never going to be very large and carrying out a sequence of individual loan renewals is not going to create performance issues. 

I think we should retain the "renew all" renewal request type (code list RNQ) in the Data Framework, to retain alignment with SIP2, but not implement this in REST. On that basis I'm inclined to close this issue.

**Comment by mdovey** [comment]
I think this may need a note to this effect in the REST implementation.

**Comment by franciscave** [comment]
The current text is as follows:

> The difference between a check-out and renewal is that in the latter case an existing, active loan of the same item to the same patron must exist. It should not be necessary for the terminal application to know whether an item is already on loan to the patron in question, because the LMS will be able to determine whether this is the case or not. A single function will therefore normally suffice.

I propose the following note be added immediately below the above text:

> NOTE - The REST web service implementation of the LCF Data Framework does not implement a mechanism for specifying the type of a renewal, which in the Data Framework is represented by element Q11D02. In the Data Framework this element serves two purposes: (a) to indicate if the request is to renew all items checked out to that patron; (b) to indicate whether the request is being made by the patron directly or by a third party. In a REST web service implementation it is not possible to request the renewal of all items in a single request, as the loan must be renewed for each item explicitly and separately. In a REST web service implementation it is not necessary to have a separate element or parameter to indicate whether it is the patron or a third party making the request, because this is already indicated by ensuring that the user making the request is authenticated in the request header.

**Comment by franciscave** [comment]
Note added to specification of REST web service implementation. See pull request #277.

**Comment by mdovey** [comment]
Closed - as agreed. Rest implementations should iterate through all loans, renewing each in turn,
