### ISSUE TITLE
Links appear to be broken in docs in both 'master' and 'develop' branches

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#128]
The links to code lists at least appear to be broken, as following a code list link produces a '404' error. This may have something to do with the fact that URIs contains '/blob' in the path. This doesn't seem to affect the published release of v1.0.1.

**Comment by franciscave** [comment]
Ah, I see! The links need to be changed to, e.g.

`[MNI](LCF-CodeLists.md#MNI)`

**Comment by mdovey** [comment]
Github pages (i.e. the published version at https://bic-org-uk.github.io/bic-lcf) converts .md to .html so I used extension-less links in case they broke. However, I've just found a page stating that links ending .md to get converted to links ending .html and tested this and it appears to work. So yes a rewrite of the URLs would ensure they would work both in the published site and the github site.

**Comment by franciscave** [comment]
If you could please review the pull request in #129, I'd be most grateful, so that we can merge the rewrites. Is there a quick way of propagating these changes to the 'master' branch, or will the edits have to be done manually?

**Comment by mdovey** [comment]
As per my comment and test (see Nov 16) this should work fine in the master link (and work with what is displayed at https://bic-org-uk.github.io/bic-lcf. So deploying to master should be fine. Although we might as well wait until we need to deploy due to other fixes.
