### ISSUE TITLE
E03 Patron - 1.0.1 defines E03D34 (Patron's home institution) as well as a E03C34 (Associated message/alert)

### ISSUE THREAD

**Issue by dkarvel** [bic-org-uk/bic-lcf#130]
E03 Patron - 1.0.1 defines 
E03D34 (Patron's home institution) as well as a 
E03C34 (Associated message/alert)

I believe there is no intention to have a composite element as well as a simple element with the same element number 34

This was found in https://github.com/bic-org-uk/bic-lcf/blob/master/docs/LCF-DataFrameworks.md

**Comment by franciscave** [comment]
Good catch! I propose that E03D34 Patron's home institution be assigned the next identifier in sequence, i.e. E03D35. This should be corrected in all documentation, including the published v1.0.1.

**Comment by anthonywhitford** [comment]
I think we should fix this by releasing v1.0.2, as this would be more
inline with good document version management.

**Comment by franciscave** [comment]
On reflection I agree. The error is not fatal for implementation of LCF v1.0.1.

**Comment by franciscave** [comment]
I've updated the IDs in the develop branch - awaiting review prior to merge.
