### ISSUE TITLE
Recommendation: Assign a new element to be re-used multiple times

### ISSUE THREAD

**Issue by dkarvel** [bic-org-uk/bic-lcf#131]
Also, a recommendation:
There is and should be an element having two sub elements: 
Amount and 
Currency

That element could be re-used on the following elements which contain Amount and Currency:
E01C14 (Check-out fee)
E02C10 (Check-out fee)
E03C20 (Charge limit)
E03C31 (Deposit balance) 
E08D07 + E08D08 (Payment amount + Payment currency)
Q13D06 + Q13D07 (Patron Payment amount + Patron Payment currency)
Q31D06 + Q31D07 (Gross charge amount + Charge currency)

**Comment by franciscave** [comment]
I'm not sure I understand what is being proposed. All the composite elements E01C14, E02C10 and E03C20 are repeatable and contain a typing element (fee type or charge type) as well as amount and currency elements. The composite element E03C31 Deposit is an exception in that it is not repeatable and only contains amount and currency elements, so could be flattened/unwrapped. Please can you clarify?

**Comment by dkarvel** [comment]
Hi Francis,
All of those elements I listed have something in common: They all have
sub-elements of two fields: currency and amount.
therefore,
We could create a generic object

<xs:element name="*whateverGenericName*">
<xs:complexType>
<xs:sequence>
<xs:element ref="amount"/>
<xs:element ref="currency" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:element>

Then we can define other elements using this new element
*whateverGenericName*
Some examples:

   - Then we can define element E01C14 as:


<xs:element name="loan-fee">
<xs:complexType>
<xs:sequence>
<xs:element ref="charge-type"/>
<xs:element ref="theamountandcurrency" type="*whateverGenericName*"/>
</xs:sequence>
</xs:complexType>
</xs:element>



   - Then we can define element  E03C20 as:

<xs:element name="charge-limit">
<xs:complexType>
<xs:sequence>
<xs:element ref="charge-type" minOccurs="0"/>
<xs:element ref="amount"/>
<xs:element name="theamountandcurrency" type="*whateverGenericName*"/>
</xs:sequence>
</xs:complexType>
</xs:element>


   - Then we can define element E03C31 as:

<xs:element name="deposit-balance">
<xs:complexType>
<xs:sequence>
<xs:element name="theamountandcurrency" type="*whateverGenericName*"/>
</xs:sequence>
</xs:complexType>
</xs:element>
It is not a problem as it is. just an improvement to reuse elements.
Thank you for your time Francis,
Dim

**Comment by franciscave** [comment]
OK, I understand now, thank you. It seems to me that there are two possible approaches:

1.  Define an additional element layer, as you describe in your comment above.

2.  Leave the existing data model as it stands, but in the XML schema define a group containing the sequence 'amount' followed by 'currency'.

I'm agnostic about this, and am happy to go along with implementers' preference between these two approaches. However, I would note that the first option would be easier to incorporate into a non-backwards-compatible upgrade to LCF, i.e. a version 2.0 rather than version 1.0.2.

**Comment by franciscave** [comment]
The Technical Panel discussed this and Matthew offered to look at implementing the second approach.

**Comment by mdovey** [comment]
This can be done for:
E01C14 (Check-out fee)
E02C10 (Check-out fee)
E03C20 (Charge limit)
E03C31 (Deposit balance)
and also
E08D07 + E08D08 (Payment amount + Payment currency)

The following aren't used in the REST version so don't apply:
Q13D06 + Q13D07 (Patron Payment amount + Patron Payment currency)
Q31D06 + Q31D07 (Gross charge amount + Charge currency)
