### ISSUE TITLE
Additions to AUT codelist for Out of hours / unmanned site access

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#133]
Need new values for AUT code list to handle issue #69  (Out of hours / unmanned site access)

**Comment by franciscave** [comment]
Colin/Neil, could you please explain the requirement again? I've read issue #69 and don't understand the requirement at all. Matthew seems to think that additional code values in code list AUT are the answer, but I can't implement that until I understand what is proposed.

**Comment by Neil-IMIL** [comment]
Hi Francis

No problem and thank you.  I don’t know if Colin will have anything to add but appreciate this.

Kind regards

Neil Johnson
Director
Insight Media Internet Limited

Tel: 0844 335 6350

http://www.insight-media.co.uk<http://www.insight-media.co.uk/>
mailto:neil@insight-media.co.uk

**Comment by franciscave** [comment]
Code value 'ACC' added to list AUT. Awaiting review.

**Comment by franciscave** [comment]
Reviewed at the Technical Panel meeting on 27/02/2019 and approved.

**Comment by mdovey** [comment]
Need to update schema

**Comment by franciscave** [comment]
I have approved the schema update, so will close this issue. However, there may be a need for a minor tweak to the documentation of this code value in the schema, once we have decided whether the next release of LCF is v1.0.2 or v1.1.
