### ISSUE TITLE
Use of lcf-patron-credential in LCF messages apart from authorisations request

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#134]
The current documentation for REST Authentication and Authorisation imply that lcf-patron-credential should only be used when requesting an Authorisation entity. However, this will need to be passed on any request where authenication is required (as REST is stateless).

Also in the case where authentication is a simple username + password (as opposed to say SAML token), should this always be passed as username:password (hexencoded) even where the username is the patron id and embedded in the URL (I would argue yes - but it would help if this was explicit)

**Comment by franciscave** [comment]
Hmm, I'm not sure about this. Now that I re-read the documentation, it looks to me as if we decided that the _Terminal_ checks what the Patron is allowed to do by requesting the Patron's authorisations. The response to this request tells the Terminal what services the Patron is authorised to use and it is the Terminal that then controls whether the Patron can access a particular service or not, by presenting only services that the Patron in question is allowed to access. A '200' response with no payload would indicate that the Patron is authorised to use general Patron services. A '200' response would only have a payload if there are specific authorisations that would not be available to all Patrons, e.g. authorisation type 'PCI' indicating that the Patron (presumably a child) has permission to access the Internet from library premises. 

Do others have the same understanding?

**Comment by mdovey** [comment]
That would be a major security hole, as it would be possible to write a "malicious" client which ignore the authorisation information and be able to e.g. check out books, obtain personal information based purely on knowing a patrons id (if I know that a library uses 8 digit barcodes, I could just interate through all combinations).

This could be mitigated by insisting all clients need to do a client authentication - however, that rules out use cases such as someone writing a generic "check my loans" app which could work with any LCF compliant system.
