### ISSUE TITLE
Additional "Suspended" entry for RVS codelist

### ISSUE THREAD

**Issue by andrewdaye** [bic-org-uk/bic-lcf#138]
Some LMS/ILS implementations allow you to suspend a reservation (i.e. it won't be filled). LCF code list RVS (reservation status) does not currently accommodate this.

Can we add "Suspended" as an additional entry to this list?

There are a couple of suspension types - those where the reservation is suspended until manually unsuspended (or "Resumed"), and those where there is suspension end date provided at the time of suspension. At that time the reservation is automatically resumed. I don't think the variation in types necessarily needs to be modelled in LCF, although we may want to add an optional suspend-end-date to the Reservation entity.

**Comment by franciscave** [comment]
Sorry for the slow response. All good questions. We should discuss these at the next Technical Panel meeting (27th February). For what it's worth, my understanding is that a reservation has the status '01' (Item available - in hold queue) when the item is ready for pickup, with a position in hold queue (E06D15) equal to 1, indicating that it has reached the top of the queue. This should probably be clarified in the documentation.

**Comment by dkarvel** [comment]
Hi Andrew and Francis, 
I am currently implementing the Reservation modules and I have to agree with both recommendations above.

So, We will also like to have the "Suspended" status (we call it "Dormant" but happy with the "Suspended" recommendation). 
We would also like (lower priority) to have the date which marks the automatic change from Suspended to Active status if any.

Can I please suggest one additional status?

InTransit - Reservation Trapped but in Transit from another location to the Pickup location.
This is similar to "Item available - in Reservation Queue" but not quite there yet. The item has been trapped for the member.

Thank you

**Comment by franciscave** [comment]
At the Technical Panel meeting on 27/02/2019 it was agreed to add a 'Suspended' status code to RVS and to add a 'suspension period' composite (optional and repeatable) containing optional start and end dates.

**Comment by franciscave** [comment]
Adding a code to list RVS is OK in v1.1.0, but can we add a new 'suspension period' composite in v1.1.0 or does this have to wait until v2.0.0? 

In my opinion adding an _optional_ element doesn't break backwards-compatibility, so this would be OK in v1.1.0. Are others happy with this?

**Comment by franciscave** [comment]
I propose the following structure for suspension period, to be added to the LCF-DataFrameworsk.md:

| *Id*       | *Element*                  | *SIP2 ID* | *Card.*                                                    | *Format*   | *Description*                  |
|-----------|----------------------|--|----|--|-----------------------------------|
|E06C16    | Suspension period |  | 0-n |  | A period during which this Reservation is suspended.|
|E06D16.1 | Start date-time      |   | 0-1 | DateTime | |
|E06D16.2 | End date-time       |  | 0-1 | DateTime | |

**Comment by franciscave** [comment]
I am presuming that, for now at least, we don't need to add a "Suspend Reservation" function to LCF. We might want to add this in future, so that a self-service terminal can be used to suspend a reservation directly, rather than this having to be done on the LMS by library staff.

**Comment by dkarvel** [comment]
Hi Francis,
Thank you for this recommendation.
Suspension is important but it can wait for the next release.

We envisage of setting the start time but not the end time as for Aurora
suspension is indefinite until the library member requests a reservation
update to lift the suspension.
Thank you
