### ISSUE TITLE
Ability to send Message\Alert for specific Loan, Item or Reservation (rather than to a specific Patron or Patron list)

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#140]
This is a particular issue for FASTEN because it is trying to use LCF messages between an LMS and Content provider without the content provider needing to know the identity of the patron

**Comment by franciscave** [comment]
That's a clear use-case for associating a message with a reservation.

**Comment by franciscave** [comment]
At the Technical Panel on 27/02/2019 we agreed to add loan and reservation reference elements (both optional and repeatable) to the Message/Alert entity.
