### ISSUE TITLE
Addition entry for CHS codelist

### ISSUE THREAD

**Issue by kjeyakanthan** [bic-org-uk/bic-lcf#141]
Some libraries have charges on the account of a patron which are not yet payable for a number of reasons. Consumers of the API will not know if a charge can be paid at the moment and may try to pay it off, which could cause complications in the payment process is the payment is collected/processed before updating the charge and the LMS rejecting this change

An additional status code in CHS of 'Not yet payable' would provide this information.

**Comment by franciscave** [comment]
Sorry about the delay in response. Holidays intervened...

I like the idea of adding a code 'Not yet payable' to CHS. What do others think?

However, it should be noted that, when making a payment using function 13 Patron payment, the payment cannot be made until authorization is received from the LMS. There first has to be a request for authorisation to make the payment and this request can be denied. In such cases the response would contain an exception condition, and the reason for denial would be given by a code value from list RDN - either '05' (no payment due) or '06' (unable to accept payment - see message). See function 13 in the LCF data framework for details.

**Comment by franciscave** [comment]
At the Technical Panel meeting on 27/02/2019 it was agreed to add a code 'Not yet payable' to code list CHS.
