### ISSUE TITLE
A Reservation can reference the Loan which completed the process but not the other way around

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#143]
The Reservation entity can reference the Loan (E06D12) which completed the Reservation workflow (where applicable), however, there is no corresponding reference in the Loan entity (i.e. to track when a Loan was related to a Reservation).

**Comment by franciscave** [comment]
True. I'm not sure what value there is in referring to a Reservation that has been fulfilled, but we generally have two-way references in LCF, so I don't see any problem in adding this.

**Comment by anthonywhitford** [comment]
Agreed.

**Comment by franciscave** [comment]
It was agreed at the Technical Panel meeting on 27th February that the Loan entity be modified to allow references to Reservations.
