### ISSUE TITLE
authorisation-code missing in xml schema for Patron

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#159]
No entry in the xml schema for authorisation-code (E03D32)

**Comment by mdovey** [comment]
In reviewing this - shouldn't this be "authorisation-ref" rather than "authorisation-code"? Am I correct in thinking that this should contain a reference to a authorisation entity?

**Comment by franciscave** [comment]
I think I got confused between the identity and type of an authorisation. In E13 the authorisation type is specified by a code from code list AUT, and this code list has the heading 'Authorisation Code'.

I think that the Authorisation entity needs a bit further thought. For example, might some authorisations need to specify a period? An authorisation of type 'ACC' might apply for a limited period.

My recollection of the detail is hazy, I'm afraid, but it's quite likely that the original idea was that an authorisation code in element E03D32 might not be a reference to an Authorisation entity, but simply a code assigned by the library. It was perhaps only later in discussing this that we decided to introduce the concept of an Authorization entity. I think we have to decide whether E03D32 is _always_ a reference to an Authorisation entity or not.

Maybe we should not try to resolve this for the imminent release. I would therefore suggest that we add 'authorisation-code' to the schema, but make it clear in the documentation that this element contains _either_ a reference to an Authorisation entity _or_ a code assigned by the library. That would leave open the following (alternative) choices for the future:

1) In v1.2 add 'authorisation-ref' and deprecate the use of 'authorisation-code' for a reference to an Authorisation entity
2) In v2.x.x change the name of 'authorisation-code' to 'authorisation-ref'.

**Comment by franciscave** [comment]
In the interests of getting to the next milestone on schedule, I'm happy to go with Matthew's proposal to rename 'authorisation-code' as 'authorisation-ref'. If we find that some implementers were expecting to be able to use either a code from list AUT directly in this element, or some library-assigned code, we can address this in the next release.

**Comment by mdovey** [comment]
My recollection (although I can't find a meeting note or issue comment to support this), was the reason we structured E13 to either have E13D02 (containing a code from codelist AUT) or E13D03 a library defined string was to allow library assigned codes in addition to the LCF defined ones, i.e. E13 effectively provides a mechanism for a library to add local authorisation codes to the AUT codelist.

So to use a LCF defined authorisation code such as parental consent E03D32 would reference an E13 entity which would look like

    <authorisation>
        <identifier>xxxx</identifier>
        <authorisation-type>PCI</authorisation-type>
    </authorisation>

whereas for a library defined code, E03D32 would reference an E13 entity such as

    <authorisation>
        <identifier>xxxx</identifier>
        <heading>local-auth-code</heading>
    </authorisation>

**Comment by franciscave** [comment]
Thanks for recalling this detail, which makes sense to me. I think it would be helpful if the description of E13D03 made this clear. I had certainly forgotten it, and it did not immediately occur to me that the intention was to use E13D03 in this way, although it does say in the Data Framework spec that this element and E13D02 are mutually exclusive. I'll add some further wording to the spec.
