### ISSUE TITLE
E12D02 wrong cardinality in XML schema

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#163]
E12D02 (name within selection criteria entity) is of cardinality 0-1 in the schema rather than 1 as in the dataframework and xml binding documentation.

This might be academic as this entity is deprecated, and perhaps should be removed from the xml schema (xml schema has no formal mechanism for indicating an element\type is deprecated).

**Comment by franciscave** [comment]
Fairly academic, but the schema should probably be consistent with the specs.
