### ISSUE TITLE
Investigate vCard support for Patron/Contact entity

### ISSUE THREAD

**Issue by anthonywhitford** [bic-org-uk/bic-lcf#17]
Raised on the LCF Technical Panel Call.

**Comment by mdovey** [comment]
XML vCard specification - https://tools.ietf.org/html/rfc6351

**Comment by franciscave** [comment]
I suggest that we deal with this issue under #41

**Comment by franciscave** [comment]
At the Technical Panel meeting on 22/09/2016 we agreed to re-open this issue.

**Comment by mdovey** [comment]
I've pushed an initial draft of an implementation into branch [lcf-17](/bic-org-uk/bic-lcf/tree/lcf-17)

**Comment by mdovey** [comment]
You can see the proposed changes at [InformationEntityXMLBindings](/bic-org-uk/bic-lcf/blob/lcf-17/docs/LCF-InformationEntityXMLBindings.md)

**Comment by mdovey** [comment]
After discussion at review group, decided not to go ahead with this unless there is a compelling case to reopen this issue

**Comment by anthonywhitford** [comment]
As per @mdovey's comment on 26 Jun 2019, the review group have decided not to proceed with this issue. Therefore removing the milestone tag and marking as "closed - not planned".
