### ISSUE TITLE
Consistent form for Added in v1.x.x

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#180]
This came up in discussion just after the 1.0.1 release. The phrase for added in v1.x.x varies between and sometimes within documents. Various forms include:

"Added in LCF v1.x.x"
"Added LCF v1.x.x"
"Added v1.x.x"
"Added in v1.x.x"

**Comment by franciscave** [comment]
Agreed. And all references to 'v1.0.2' need to be changed to 'v1.1.0', if that is what we are now about to release.

**Comment by franciscave** [comment]
I think I prefer 'Added in v1.x.x' to the other alternatives. Similarly '... corrected/changed in v1.x.x'.

**Comment by franciscave** [comment]
Should we make this change after merging all the other v.1.1.0 changes? That would significantly reduce the number of documents (in different branches) that need to be edited.

**Comment by mdovey** [comment]
Yes.
