### ISSUE TITLE
Call number in item entity

### ISSUE THREAD

**Issue by kjeyakanthan** [bic-org-uk/bic-lcf#189]
Are we able to add a call number field to the item entity please. A lot of libraries have specific call numbers for each of their items.

**Comment by franciscave** [comment]
Am I right in thinking that a "call number" is a kind of item identifier? If so, it is already possible to include this as an additional identifier (E02C02). In that case we might wish to define a new code value for list IMI, although if each library has its own conventions for call numbers, it might be best to simply use the existing code value '01' (IMI01 proprietary).

**Comment by jeremylangley** [comment]
Yes. "Call number" is an item identifier, or shelf locator. For us within ILS/LMS, call number is a combination of one or more of the following dewey class, LCC, prefix, suffix. This number may not be uniform for items assoicated to a manafestiation, and each item may have unique call number.

**Comment by Mickfortune** [comment]
From memory (based on working for US companies for 20 years) call numbers are mostly used in North America so we Europeans never paid much attention to their format. As I understand it libraries can construct their own formats - indeed may have to do this if they use physical location as part of the call number (Glasgow University once designed a classification system based on rooms). So uniformity of call numbers on manifestations would be unlikely.

What I’m not sure about is whether multiple copies of an item always identify themselves in the same way (e.g. with a numerical suffix) - or whether they all share the same call number? You say ‘may have a unique call number” which implies they may not?

Not sure that matters if the call number is not the unique identifier used for circulation control?

Mick

**Comment by franciscave** [comment]
So, is it sufficient to consider this a proprietary item identifier, without knowing that it is the "call number"? Or would it be better to indicate that this identifier is the call number, by assigning a different code value to the item identification scheme? If the latter, we would modify code list IMI something like the following:

  *Code ID*   |*Code value*   |*Definition*   |*Notes*
  ----------- |-------------- |-------------- |---------
  IMI01       |01             |Proprietary    |
  IMI02       |02             |Call number  |A library-specific item identifier

**Comment by Mickfortune** [comment]
I think the latter, but this is likely to be a bigger concern for North American users so I’d welcome their input.

**Comment by franciscave** [comment]
I discussed this with @anthonywhitford and we wonder whether the use of 'call number' is consistent enough across the library sector to warrant a separate IMD code value. The use of IMD01 (Proprietary) might be sufficient. We also wonder whether in some cases the call number is not in fact an item identifier at all, but is a _location_ identifier, e.g. identifying a specific location on a shelf. If several items share the same call number because they belong in essentially the same shelf location, that would be a location identifier rather than an item identifier, and would need to be represented using E02C06 Associated location rather than E02C02 Additional identifier.

**Comment by mdovey** [comment]
Agreed to close by Review Group, as we believe the issue to have been addressed.

**Comment by anthonywhitford** [comment]
As this issue was closed in 2020 with no further action planned, I'm removing the "someday.minor" milestone.
