### ISSUE TITLE
Inconsistency for E03C24

### ISSUE THREAD

**Issue by kjeyakanthan** [bic-org-uk/bic-lcf#190]
Library card status information (E03C24) in Patron entity has cardinality of 0-nR in the xml binding but 0-1R in the DataFramework. 

I would think 0-1 is right as your card status can only be in one status

**Comment by franciscave** [comment]
I agree that this is a typo in the Data Framework. Will be fixed in the next version. The XML schema is consistent with the XML binding, so neither of those needs fixing. Thanks for catching this.

**Comment by franciscave** [comment]
Hmm, sorry, I misinterpreted the original comment, which was that the Data Framework is correct and the XML binding and schema are incorrect. To correct this requires a breaking change in the schema, so in the next minor release of LCF we should simply deprecate the inclusion of more than one instance of E03C24 Library card status information.
