### ISSUE TITLE
Function 18 Set/reset patron PIN not documented in Data Framework

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#192]
Function 18 was added to the REST implementation in LCF v1.0.1, but was not documented in the Data Framework. This needs to be added.

**Comment by franciscave** [comment]
Here is my proposed revision to the LCF Data Framework:

### <a name="f18"></a> 18 Set/reset patron PIN
Back to functions list

This function sets the PIN associated with a Patron entity. Since, for security reasons, this PIN may not be held as a property of the Patron entity, it cannot be set or retrieved using any of the core functions.

#### Request

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|------------|----------------------|------------|---------|-----------|---------------------------------|
| **Q18D01** | **Patron reference**    |         | **1**   | **String**|                                 |
| **Q18D02** | **Patron PIN**        |            | **1**   | **String**| Encrypted PIN              |

#### Response

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|------------|----------------------------|------------|---------|-----------|---------------------------------|
| R18D01 | Patron reference       |                  | 0-1       | String       | The identifier for the Patron record for which the PIN has been successfully set/reset.                                               |

**Comment by mdovey** [comment]
Why do we return patron reference in the response (I see it is optional), given that only one patron reference can be specified in the request.

In the REST implementation we only return success (HTTP 200) or an error

**Comment by franciscave** [comment]
On reflection I feel that R17D01 and therefore R18D01 are both unnecessary, because in the protocol-neutral Data Framework a response can already include a functional acknowledgement R00D02, indicating whether the request was successful or not, and this more closely corresponds to HTTP response codes in the REST implementation. However, this makes me wonder whether the following elements should be made optional in the Data Framework, since a functional acknowledgement is going to be all that is needed in most implementations:

  -  R03D01
  -  R03D02
  -  R04D01
  -  R04D02
  -  R05D01
  -  R05D02
  -  R14D01
  -  R15D01

**Comment by mdovey** [comment]
I'm closing this as the initial problem is now resolved. The broader issue concerning possibly redundant response elements is continued in #226
