### ISSUE TITLE
Retrieving selection criteria using LCF function 25 in REST implementation

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#193]
The REST implementation includes function 25, which indicates that 'properties' is the keyword for entity type E12. But this entity type is currently deprecated in LCF, and 'properties' is not listed in code list ENT. Should the use of function 25 currently be deprecated? If we're going to define a query language for selection criteria (see issue #113), maybe we can use function 25, but it isn't immediately clear whether and how we would do this.

**Comment by franciscave** [comment]
We should probably review function 26 at the same time.

**Comment by mdovey** [comment]
25 needs to be removed\deprecated in both the Rest implementation and the underlying data framework.

**Comment by franciscave** [comment]
Agreed. I will adjust the documentation.

**Comment by franciscave** [comment]
*Proposed documentation change for the Data Framework:*

### <a name="f25"></a> 25 Retrieve selection criterion type list
\[*Deprecated in v1.2.0*\]

[Back to functions list](#functions)

This function is the same as the core function 02 for retrieving a list of entities of type E12 Selection criterion.

NOTE - (*Added in v1.2.0*) Implementation of this function is now deprecated. A new approach to the expression of search and selection criteria for the retrieval of lists of entities is to be added in a future version.

### <a name="f26"></a> 26 Retrieve list of available items at a specific location
\[*Deprecated in v1.2.0*\]

[Back to functions list](#functions)

This function selects all items that are available to be borrowed at a specific location and is the same as function 25 with specific Selection criteria: a specific location and a specific circulation status (CIS03 = 'Available').

NOTE - (*Added in v1.2.0*) Implementation of this function is now deprecated. A new approach to the expression of search and selection criteria for the retrieval of lists of entities is to be added in a future version.

...

*Proposed documentation change for the REST implementation:*

25 Retrieve selection criterion type list
-----------------------------------------
\[*Deprecated in v1.2.0*\]

<span id="h.1fob9te" class="anchor"></span>This function is the same as the core function 02 for retrieving a list of selection criterion entities. A list of selection criterion types can be retrieved for a specific entity type or for all entity types, e.g.:

    GET http://192.168.0.99:80/lcf/1.0/properties?entity-type=manifestations
    
    GET http://192.168.0.99:80/lcf/1.0/properties?entity-type=locations

NOTE - (*Added in v1.2.0*) Implementation of this function is now deprecated. A new approach to the expression of search and selection criteria for the retrieval of lists of entities is to be added in a future version of LCF.

26 Retrieve list of available items at a specific location
----------------------------------------------------------
\[*Deprecated in v1.2.0*\]

The following selects all items that are available to be borrowed (circulation-status = '03') and are at a specific location 'shelf1':

    GET http://192.168.0.99:80/lcf/1.0/items?current-location=shelf1&circulation-status=03

NOTE - (*Added in v1.2.0*) Implementation of this function is now deprecated. A new approach to the expression of search and selection criteria for the retrieval of lists of entities is to be added in a future version of LCF.

...
