### ISSUE TITLE
E15C12 missing from the Information Entities XML bindings

### ISSUE THREAD

**Issue by kjeyakanthan** [bic-org-uk/bic-lcf#199]
Looks like E15C12 is defined as Message/alert text in the Data Framework but missing in the XML bindings although E15D12.1 and E15D12.2 is defined in both

**Comment by franciscave** [comment]
Good catch! Will be fixed in the next release. Curiously, the XML schema doesn't contain this error, so my guess is that this got deleted in the XML binding specification by mistake at some point.
