### ISSUE TITLE
Refine semantic versioning model for REST URL and specific implementation versions

### ISSUE THREAD

**Issue by anthonywhitford** [bic-org-uk/bic-lcf#201]
In #Plugfest 3 we discussed the semantic versioning model, and highlighted that the version number in the REST URL would remain at 1.0, as changing this would make the version change itself a breaking change. 

We briefly discussed the need for a service to confirm the specific implemented version number, so terminals were able to understand precisely what they should expect. @andrewdaye also confirmed that is was valid and helpful to also have the major version number on the URL, as some implementations may use this as a version selector, essentially asking the server to respond in kind. 

We took this offline for the Technical team to review and propose a solution.

**Comment by franciscave** [comment]
Proposal: add an 'lcf-version' header field to all responses, including error responses. Consider adding this same field to the request header.
