### ISSUE TITLE
Question: How would a developer know which REST services require the lcf-patron-credential header?

### ISSUE THREAD

**Issue by anthonywhitford** [bic-org-uk/bic-lcf#202]
In #Plugfest 3 the question was asked about how would a client know whether it was required to provide the lcf-patron-credential header. This would need to be described within the LCF standard, so this is clear for all parties.

**Comment by franciscave** [comment]
If you omit the lcf-patron-credential header and one is required, you should get an HTTP 403 response, indicating that the header is either missing or incorrect. There's an error in the second paragraph: 401 should be 403.

**Comment by MarkOliver** [comment]
If the lcf-patron-credential header is optional on all services then someone could implement the LCF standard and not implement any service that implements that header.  As an application developer I would then have no way for my application to authenticate the credentials that a user has presented me with, which was the original use case for this requirement.

Also if I provided the lcf-patron-credential-header and I get back a 200 am I to be sure that this means that the credentials were validated and not just ignored if the service doesn't need them?

**Comment by franciscave** [comment]
I can see that a 200 response might mean either that the credentials are valid or that they have been ignored by the server. Since we're talking about response to an LCF-specific header field in the request, maybe the solution is to include a non-standard LCF-specific header field in the response, e.g. 

    HTTP/1.1 200 OK
    lcf-patron-verification: OK

A response that did not contain this header field would indicate that patron verification was not implemented on this server for the service requested. 

An alternative would be to consider a two-stage request, enabling the terminal to be sure that the patron's credentials are verified before proceeding with the service request:

    GET /lcf/1.0/patrons/{id-value}
    lcf-patron-credential: BASIC cGF0cm9uLWlkOnBhc3N3b3Jk
    Expect: 100-continue

and in the response:

    HTTP/1.1 100 Continue
    lcf-patron-verification: OK

However, I'm not certain that this additional stage would be useful.

**Comment by MarkOliver** [comment]
I have no issue with either of those implementations.  My concern is that the LCF standard should specify at least one service request that must support the chosen implementation.

**Comment by mdovey** [comment]
One possible scenario for LCF might be to allow library staff to manage the LMS from designated terminals (access to which is secured by other means). In this case LCF would be using terminal authentication for all services, without using patron level authentication.

**Comment by mdovey** [comment]
Also, on reflection I think the idea of using 401 and 403 to distinguish breaks the usual semantics of the HTTP error codes.

Having reviewed HTTP 403 it should be used for authorisation errors not authentication errors.

I.e. a 403 returned for either a patron or terminal authentication means that although the authentication (username\password) was correct the patron or terminal is not allowed to do that operation.

**Comment by franciscave** [comment]
See #205.

**Comment by mdovey** [comment]
After discussion, the proposed solution (to add to the documentation) is as follows:

The client should attempt the operation with no authentication information (neither terminal via HTTP Basic or user via lcf-patron-credential HTTP header) (taking care if the operation would make updates etc.)

A response of 200\201 means that no authentication is required.
A response of 401 means that a terminal authentication is required.
A response of 403 means that a patron authentication is required.

(if both terminal and patron authentication is required, the server may respond with either 401/403, and may respond to a subsequent request with a similar message should the client send only one of the required authentication).

**Comment by mdovey** [comment]
at the technical panel discussion on 11/6/2019, the general approach above was accepted.

However, it was discussed that there may need to be a profile which defined an operation which would always need Patron authentication for when LCF was being used for authentication purposes. Use cases would be needed.
