### ISSUE TITLE
Implementation profiles - core profile defined at Plugfest #3

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#203]
Here are my notes on  the core profile for LMS implementation of LCF that was developed and discussed during the Plugfest on 15 May 2019:

| Core&nbsp;function:       | 01<br/>Retrieve/View entity instance information | 02<br/>Retrieve entity instance list | 03<br/>Create entity instance | 04<br/>Modify entity instance | 05</br>Delete entity instance|
|---------------------------|----|----|----|----|----|
| E01<br/>Manifestation |  y  |  y  |      |      |      |
| E02<br/>Item                |  y  |  y  |      |  y  |  *  |
| E03<br/>Patron             |  y  |  y  |  y  |  y  |  y  |
| E04<br/>Location          |  y  |  y  |      |      |      |
| E05<br/>Loan                |  y  |  y  |      |      |      |
| E06<br/>Reservation     |  y  |  y  |  y  |  *  |  y  |
| E07<br/>Charge            |  y  |  y  |  y  |      |  *  |
| E08<br/>Payment          |  y  |  y  |  y  |      |      |
| E09<br/>Contact           |  y  |  y  |  y   |  y  |  *  |
| E13<br/>Authorization  |  y  |  y  |      |      |      |
| E14<br/>Authority/Inst. |  y  |  y  |      |      |      |
| E15<br/>Message/alert |  y  |  y  |  *   |  *  |  *   |

y = Support required in all core profile implementations.
*&nbsp;= Support required for some extensions of the core profile, e.g. for CRM solutions.

Does this make sense?

An LMS supports a core function for a specific entity type if it supports the use of that function by at least some terminal devices/applications.

**Comment by franciscave** [comment]
In discussion with Matthew we agreed that support for functions marked with an asterisk are not part of the core profile. They may feature in other profiles added at a future date.

**Comment by mdovey** [comment]
Discussed at Review Group, and added to non-normative documentation
