### ISSUE TITLE
Patron circulation/account summary: a case for a new entity?

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#204]
At the recent Plugfest there was discussion about whether a new entity type should be added to LCF to enable terminal applications to retrieve a patron circulation/account summary, containing a combination of information from different entity instances relating to a single patron, avoiding the need to carry out a series of retrievals.

This feels like a different kind of thing to the entity types we have defined so far, in that all the properties of this entity are essentially properties of other entities. The core functions don't seem to apply to it: it is effectively read-only, so modifying it would not make any sense. I'm wondering whether we should be treating this as something different from an entity, perhaps a kind of "view" or "filter".

Thoughts, anyone?

**Comment by mdovey** [comment]
Agreed at technical panel (11/6/2019) that this was a specific solution to issue #191 and therefore in scope for a more general solution to being able to specify which attributes of an entity and its sub entities to retrieve.

**Comment by anthonywhitford** [comment]
Removing the milestone "Someday.Major" as any further work will be done under issue #218.
