### ISSUE TITLE
Add json as valid payload syntax in addition to xml

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#206]

**Comment by mdovey** [comment]
Unverified json implementation can be found at http://lcf.ceridwen.com/lcfserver-server-1.1.0-SNAPSHOT/swagger-ui.html

**Comment by mdovey** [comment]
It was agreed by the technical panel to include the generated OpenAPI from https://lcf.ceridwen.com/lcfserver-server-1.2.0-SNAPSHOT/openapi.json to the documentation

**Comment by anthonywhitford** [comment]
Removed milestone "Someday.Major" and listed against milestone "LCF 1.3" as the intended work was delivered under this milestone.
