### ISSUE TITLE
Do we need classification scheme and classification code entities

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#207]
At the May 2019 PlugFest, whether LCF would need these was questioned:

i) it is unlikely LCF would be used for managing these (so these would be read only)
ii) there weren't clear use cases for an LCF client to retrieve these (and codes could be a very long list)

**Comment by franciscave** [comment]
My understanding is that most libraries use one or more of a limited number of widely-used classification schemes (e.g. DDC, UDC, LCC). We already have an LCF code list ([LCS](https://github.com/bic-org-uk/bic-lcf/blob/develop/docs/LCF-CodeLists.md#LCS)) for identifying classification schemes and this could be readily extended (and probably should be extended to include UDC and LCC), and the code value '01' (Proprietary) can be used for local schemes.

I cannot see a case for retaining E11 Classification term, so I think this entity should be deprecated.

I can see a possible case for retaining E10 Classification scheme, as it would enable a list of classification schemes used by a library to be retrieved, together with potentially useful information such as which of a library's collections employ which classification scheme. However, in this case I think we would need to add more properties to E10 to identify the scheme type with reference to code list LCS (compare with E01C10) and the collections on which the scheme is employed. 

This could be argued to be attempting to define a use case for LCF in the cataloguing area, something that we have not identified as a legitimate use case.

**Comment by mdovey** [comment]
Decision at the 11/06/2019 Technical Panel was to deprecate these entitys
