### ISSUE TITLE
Cancelling reservations and payments

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#213]
At present it is possible to cancel a check-in or a check-out because both allow for inclusion of a reference to the loan (and any associated charge) to be cancelled.

However, the same does not apply to cancelling a reservation, because the request Q16 doesn't allow for inclusion of a reference to an existing reservation. I think this is an error. 

The same might apply to cancelling a payment, because Q13 cannot refer to an existing payment, but in this case it could be argued that cancellation is not possible, as the payment transaction is presumably not reversible, except by creating a new charge.

**Comment by franciscave** [comment]
The following adds Q16D11 reservation reference to the cancel reservation request:

| *Id*       | *Element*                  | *SIP2 ID*  | *Card.* | *Format*  | *Description*                   |
|------------|----------------------------|------------|---------|-----------|---------------------------------|
| ... |            |    |   |           |
| Q16D07     | Pick-up location reference | BS         | 0-1     | String    | The LCF entity identifier of the location where the items are to be picked up by the patron. Normally only included if the reservation type is ‘04’, either instead of or additional to Q16D06.                                                                     |
|Q16D11      | Reservation reference     |            | 0-1     | String        | Mandatory when cancelling a reservation |
| Q16D08     | Reservation start date     |            | 0-1     | DateTime  | Only used in confirmations.     |
| ... |            |    |   |           |

**Comment by mdovey** [comment]
In the REST implementation, cancelling a reservation is simply a matter of updating the reservation status, as is the case for loans etc.

This is therefore an issue with parts of the underlying data-framework which aren't mapped to REST. There is an argument that this aspects of the data framework should be simplified and pruned, particular in this case, where there is an alternative (modify status) which both achieves the same aim, and is consistent with the data framework.

**Comment by mdovey** [comment]
Closing this, as related to underpinning dataframework aspects not in REST which should be covered in #118

**Comment by anthonywhitford** [comment]
Removing milestone "someday.minor" as there is no further work planned and expected work was completed under #118
