### ISSUE TITLE
lcf-check-out-response oddities

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#214]
lcf-check-out-response allow you to either include (embed) the created loan record, or include a reference to the created loan record. Unlike, lcf-check-in-response which only allows you to specify a reference to the modified loan.

I vaguely recall some discussion about whether we really needed two ways to achieve the same thing in these response, but not the outcome.

More oddly, the description for lcf-check-out-response stated that One of R11D01, R11C02 or R11D03 must be included in the response. As R11D03 is media-warning this doesn't seem right.

**Comment by franciscave** [comment]
I agree that there's an apparent inconsistency between the various responses specified in REST for 11 Check-out item, 12 Check-in item and 16 Reserve item. 

In the Data Framework both 11 Check-out item and 16 Reserve item allow the response to contain either a reference to the created loan / reservation entity or the entity itself, but 12 Check-in only allows the response to contain a reference to the modified loan.

However, I note that the REST response to both 03 Create entity and 04 Modify entity can contain either a Location header field, pointing to the created/modified entity, or the entity itself as the response payload. One could therefore argue that the way that 11 Check-out and 16 Reserve item are specified in REST is consistent with 03 Create entity (loan / reservation), whereas the way that 12 Check-in is specified is not consistent with 04 Modify entity (loan). It might therefore be more consistent to allow the check-in response to contain the modified loan entity. This would require a documentation change in both the Data Framework and in the REST implementation, as well as a schema change.

On your point regarding the odd note against R11D01 loan-ref in the REST specification, this is inconsistent with the LCF specification and I think we should simply treat this as an editorial error and therefore a patch-level change from "R11D01, R11C02 or R11D03" to "R11D01 or R11C02".

**Comment by mdovey** [comment]
A few things.

the alternative response for reservations was deprecated, so the only value payload is a reservation xml structure, the alternative formats for checkin\out were retained to pass the media warning, security desensitize, spatial attention and related charge data.

A 03 Create entity response must always contain a Location header field (if successful)
A 04 Modifty entity response should never contain a Location header field 
(the above pretty much follows from the definitions of the relevant HTTP response codes 201 and 200)

Both 03 Create and 04 Modify may (optionally) contain the created\modified entity in the payload.

However, as a check-out\renewal is always a 03 Create, the response must always contain a Location header. The presumably would always be a reference to the relevant Loan record (since the check-out-response format is not a persistent entity and not referencable). R11D01 therefore duplicates the information which would be in the Location header and is redundant.

**Comment by mdovey** [comment]
My proposal would be to

i) deprecate R11D01 (as it duplicates information which would be in the required Location http header)
ii) make R11D02 cardinality 1. The choice is whether to return a payload or no payload. It you are returning a payload it should either be a Loan entity, or a Loan entity plus additional information (i.e. loan wrapped in the lcf-check-out-response)
iii) likewise for lcf-check-in-response, either change R12D01 to be Loan rather than Loan-ref (or deprecate and replace)

**Comment by franciscave** [comment]
This is being addressed under issue #227.
