### ISSUE TITLE
Profile defining end point for patron authentication

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#217]
Off shoot issue from issue #202 

For certain purposes (e.g. authentication, SSO), a well known operation which would always required patron level authentication would be needed.

There may be reasons whilst it is not appropriate for the LCF specification to specify this, so this would be an obvious candidate for an implementation profile.

**Comment by franciscave** [comment]
In LCF 1.0 it would be simplest to define a profile for this. The alternative would be to define a new or existing operation that always requires authentication, but this would probably be easier to achieve in a major revision.

**Comment by mdovey** [comment]
Section 4 which not covers this, needs some additional text to clarify the use of

/lcf/1.0/patrons/{id-value}/authorisations

which returns valid authorisations for the authenticated patron, versus

/lcf/1.0/authorisations

which return the full list of valid authorisation codes on the LMS

**Comment by mdovey** [comment]
Section 4 which now covers this, needs some additional text to clarify the use of

/lcf/1.0/patrons/{id-value}/authorisations

which returns valid authorisations for the authenticated patron, versus

/lcf/1.0/authorisations

which return the full list of valid authorisation codes on the LMS

**Comment by franciscave** [comment]
I agree that this is a special case that needs some description.

I suggest that the text describing Patron authorisation be modified as follows:

#### 4. Patron Authorisation (Access Rights and Privileges) *(added in 1.2.0)*

Authorisation requests are initiated with a GET request to /lcf/1.0/patrons/{id-value}/authorisations

<em>NOTE: A GET request to /lcf/1.0/authorisations, which does not explicitly specify a Patron, will not achieve the desired result, as it will return a list of Authorisations supported by the LMS without indicating which ones are being granted to the Patron in question.</em>

The response to a successful Authorisations request is a list of zero or more [AUTHORISATION entities](LCF-Dataframeworks.md#E13) being granted to the specified Patron. 

Each AUTHORISATION entity within the list must state which authorisation is being granted. There is currently a controlled list (code list [AUT](LCF-CodeLists.md#AUT)) of common authorisations which can be used in an [AUTHORISATION entities](LCF-Dataframeworks.md#E13), although an implementation may extend this with custom [AUTHORISATION entities](LCF-Dataframeworks.md#E13).

Implementations SHOULD only provide a list of [AUTHORISATION entities](LCF-Dataframeworks.md#E13) after a successful Patron Authentication (see above). As such this operation MAY be used for Patron authentication purposes.

```
GET /lcf/1.0/patrons/{id-value}/authorisations
Authorization: BASIC {Base64-encoded-terminal-credentials}=
lcf-patron-credential: BASIC {Base64-encoded-patron-credentials}

Responds with:
HTTP/200
Where the Body / Payload is an authorisation entity response. Note that the authorisation entity response could be empty, indicating that there are no authorisations granted.

-- or --

HTTP/401 - Service Terminal credentials were invalid, or need to be obtained from the IdP again

-- or --

HTTP/403 - The id-value and password\pin combination are invalid, or need to be obtained from the IdP again

-- or --

HTTP/404 - the Patron represented by id-value does not exist
```
