### ISSUE TITLE
Create a base abstract type for entities

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#224]
A comment from Anthony at the plugfest suggested that he expected the LCF entities to be derived from a base XML type (since they all have an identifier). This isn't quite the case. The current xml schema (removing documentation) is of the form

```
    <xs:element name="authorisation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="identifier" minOccurs="0"/>
                <xs:group ref="authorisation-props"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:group name="authorisation-props">
        <xs:sequence>
            <xs:element ref="authorisation-type" minOccurs="0"/>
            <xs:element ref="heading" minOccurs="0"/>
            <xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>
```

This could be replaced with an inheritence model. Keeping the ...-props groups this would look like:

```
    <xs:complexType name="lcf-entity" abstract="true">
        <xs:sequence>
            <xs:element ref="identifier" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="authorisation">
        <xs:complexType>
            <xs:complexContent> 
                <xs:extension base="lcf-entity">
                    <xs:group ref="authorisation-props"/>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
    <xs:group name="authorisation-props">
        <xs:sequence>
            <xs:element ref="authorisation-type" minOccurs="0"/>
            <xs:element ref="heading" minOccurs="0"/>
            <xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:group>
```

Alternatively removing the groups would look like

```
    <xs:complexType name="lcf-entity" abstract="true">
        <xs:sequence>
            <xs:element ref="identifier" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="authorisation">
        <xs:complexType>
            <xs:complexContent> 
                <xs:extension base="lcf-entity">
                    <xs:sequence>
                        <xs:element ref="authorisation-type" minOccurs="0"/>
                        <xs:element ref="heading" minOccurs="0"/>
                        <xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:extension>
            </xs:complexContent>
        </xs:complexType>
    </xs:element>
```

The xml in all three cases should look the same.

**Comment by franciscave** [comment]
Given that the base type only contains a single element (identifier), I am puzzled as to what the value is in using an abstract type in this case. It doesn't appear to make the XSD any simpler. Rather the reverse. Maybe it helps build data structures from the XSD in some development environments?

**Comment by mdovey** [comment]
It can be helpful in programming languages to either have a base type for the entities, or a way of accessing the identifier of a a generic entity.

For example, the follow code (using the suggested xml schema change) would allow a generic way of automatically generating the identifier during a POST (creation) request:


    void POST(LcfEntity entity) {
        String generatedId = UUID.randomUUID().toString();
        entity.setIdentifier(generatedId);

        // process\store entity


Under the existing schema, this would look either like:

        String generatedId = UUID.randomUUID().toString();
        
        if (entity instanceof Manifestation) {((Manifestation)entity).setIdentifier(generatedId);}
        if (entity instanceof Item) {((Item)entity).setIdentifier(generatedId);}
        if (entity instanceof Patron) {((Patron)entity).setIdentifier(generatedId);}
        if (entity instanceof Location) {((Location)entity).setIdentifier(generatedId);}
        if (entity instanceof Loan) {((Loan)entity).setIdentifier(generatedId);}
        if (entity instanceof Reservation) {((Reservation)entity).setIdentifier(generatedId);}
        if (entity instanceof Charge) {((Charge)entity).setIdentifier(generatedId);}
        if (entity instanceof Payment) {((Payment)entity).setIdentifier(generatedId);}
        if (entity instanceof Contact) {((Contact)entity).setIdentifier(generatedId);}
        if (entity instanceof Authorisation) {((Authorisation)entity).setIdentifier(generatedId);}
        if (entity instanceof Authority) {((Authority)entity).setIdentifier(generatedId);}
        if (entity instanceof MessageAlert) {((MessageAlert)entity).setIdentifier(generatedId);}

        // process\store entity

Or a shorter approach (but not ideal) using introspection:

        String generatedId = UUID.randomUUID().toString();

        try {
            Method method = entity.getClass().getMethod("setIdentifier");
            method.invoke(entity, generatedId);
        } catch (NoSuchMethodException | SecurityException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(LCF.class.getName()).log(Level.SEVERE, null, ex);
            // report error
        }
        
        // process\store entity

In terms of keeping the xml simple, I'm not sure why we have the groups approach. The simplest xml schema would have been:

    <xs:element name="authorisation">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="identifier" minOccurs="0"/>
                <xs:element ref="authorisation-type" minOccurs="0"/>
                <xs:element ref="heading" minOccurs="0"/>
                <xs:element ref="note" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


As it stands the current structure seems to hint (to the human reader) that all entities have an identifier, but without providing this information in a machine readable way that programming tools would take advantage of
