### ISSUE TITLE
Redundant response elements in Data Framework

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#226]
In the protocol-neutral Data Framework a response can already include a functional acknowledgement R00D02, indicating whether the request was successful or not, closely corresponds to HTTP response codes in the REST implementation. Since a functional acknowledgement is going to be all that is needed in most implementations, the following may all need to be optional:

R03D01
R03D02
R04D01
R04D02
R05D01
R05D02
R14D01
R15D01
R17D01
R18D01

(see #192 for background)

**Comment by franciscave** [comment]
R17D01 and R18D01 already have cardinality 0-1. I think that we should change the cardinalities on the other elements to 0-1 in v1.2.0, as the fact that they are currently mandatory in the Data Framework is inconsistent with the REST implementation. I would prepare a pull request for this.
