### ISSUE TITLE
Revise description of Check-out to be clearly non-prescriptive

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#227]
The LCF Version 1.0.1 specification currently gives considerable detail of what entities are affected by a specific function such as check-out. This needs to be revised to be clear that this is indicative, but ultimately the business logic should be determined by the library system.

(see also issue #77)

**Comment by franciscave** [comment]
This affects the descriptions of functions 11 (Check-out/renewal), 12 (Check-in) and 13 (Patron payment).
