### ISSUE TITLE
Question: When will 1.2 be finalised?

### ISSUE THREAD

**Issue by MarkOliver** [bic-org-uk/bic-lcf#242]
When will version 1.2 be finalised and "published" to https://bic-org-uk.github.io/bic-lcf/ ?

**Comment by franciscave** [comment]
Version 1.2 is expected to be finalised and published following a meeting of the LCF Review Group later today (5 November).

**Comment by franciscave** [comment]
At the Review Group meeting yesterday it was agreed that LCF v1.2.0 would be published by the end of November. The Review Group needs to review the most recent changes to the expression of library opening/closing times in entity E14 Library Authority/Institution, and following that the editors need some time to do the necessary technical work to publish LCF v1.2.0.
