### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by colinparkeruk** [bic-org-uk/bic-lcf#246]
Add ability for a patron to make donations, as opposed to adding credit to their own account.

**Comment by franciscave** [comment]
Donations to another Patron's account? Or to the library?

**Comment by colinparkeruk** [comment]
The customer request was 'accept donations' so I assume this is for donations to the library.

**Comment by franciscave** [comment]
My suggestion would be to add an optional element 'Payment purpose' to the Payment entity. This would use a new code list for which at present we would have two values: a default value '00' indicating that the purpose of the Payment is to credit the Patron's account with reference to any specific Charges that are referred to in the Payment; a value '01' would indicate that the purpose of the Payment is to make a donation to the library authority/institution. 

An optional element to identify the Library Authority/Institution entity to which the donation is being made could also be added.

The new code list could be extended to make payments for other purposes, e.g. where the library is acting as a payment collection agent on behalf of other authorities/public services.

To generalise this further, there might be a case for the entity E14 Library Authority/Institution to be generalised to allow for non-library authorities/institutions/services to be supported.

**Comment by franciscave** [comment]
At the Technical Panel meeting on 11 February it was agreed to implement my proposal.

**Comment by franciscave** [comment]
Now implemented in pull request #253.
