### ISSUE TITLE
Add UPC as option in MNI Manifestation identification scheme (from ONIX Code List 5)

### ISSUE THREAD

**Issue by andrewdaye** [bic-org-uk/bic-lcf#255]
Proposal to add an option for UPC in the MNI manifestation identification scheme. 

Following the existing precedent, suggest "04" as the code value to match the other entries in pulling from ONIX code List 5 as detailed in https://ns.editeur.org/onix/en/5

This would support the display of DVD (amongst other non-book) cover images and related information in a discovery platform.

**Comment by franciscave** [comment]
I see no problem with this. I have reviewed ONIX Code List 5 and I believe that the only other code values that might be useful in a UK context are "24" (Co-publisher's ISBN) and "25" (ISMN-13). However, with FASTEN in mind, we might need to consider adding other code values that are used by north American libraries.

I'll await the outcome of review by the Technical Panel before adding this to code list MNI in the 'develop' branch.

**Comment by franciscave** [comment]
Following discussion at the Technical Panel meeting on 19 March 2020, I have reviewed which ONIX code lists are used by LCF *in their entirety* and which are subsetted:

- Code list 17 is used in its entirety by element E01D05.1 Manifestation contributor role.
- Code list 150 is used in its entirety by element E01D03.3 Manifestation media type code, if indicated by E01D03.1 Manifestation media type scheme (LCF code list MES, value '03')
- Code list 175 is used in its entirety by element E01D03.3 Manifestation media type code, if indicated by E01D03.1 Manifestation media type scheme (LCF code list MES, value '04')
- A subset of code list 5 is used by element E01D02.1 Manifestation identifier type (the main focus of this issue) (LCF code list MNI).
- A subset of code list 15 is used by element E01D06.1.1 Manifestation title type (LCF code list TTL).
- A subset of code list 19 is used by element E01D05.3 Manifestation unnamed contributor type (LCF code list UNC - Note that reference to ONIX code list 11 is a typo).
- A subset of code list 44 is used by element E03D27.1 Patron identifier type (LCF code list PNI).

Where an ONIX code list is used in its entirety, it is not included explicitly in the LCF code lists. In the case of E01D05.1 Manifestation contributor role, there is simply a reference to the current ONIX code lists on the EDItEUR website (see note [\[5\]](https://github.com/bic-org-uk/bic-lcf/blob/develop/docs/LCF-DataFrameworks.md#Notes) in the LCF Data Framework).

I think there is a case for proposing that ONIX code lists 5, 15 and 19 should be adopted in their entirety, and while this means that the schema will have to be kept up-to-date, the explicit LCF code lists will become redundant.

Regarding ONIX code list 44, this is a general list of name identifier schemes, and is intended to be subsetted for use in different contexts, so I propose that we continue to maintain an explicit LCF subset of this code list.

**Comment by franciscave** [comment]
At the Technical Panel meeting on 14 May 2020 we agreed that, in addition to ONIX code list 17, LCF should support ONIX code lists 5, 15 and 19 in full. The subsets of these ONIX code lists, which are currently specified as LCF code lists MNI, TTL and UNC, will therefore be removed from the next issue of the LCF code lists. These code lists in full will be added to the ONIX code lists module of the LCF XML schema.
