### ISSUE TITLE
Possible omission in Core LMS Profile

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#261]
As currently documented, cancellation of a check-out (see LCF Rest Web Service Specification, function 11) involves the client issuing an HTTP DELETE request to the server to delete the Loan record that was created earlier using an HTTP POST request for the check-out.

The Core LMS Profile (P00) excludes the capability to delete a Loan instance.

Is the ability to cancel a check-out something that should be part of the Core LMS Profile? If so, either deleting a Loan instance should be supported, or the use of an HTTP DELETE request in function 11 is incorrect. On the assumption that the latter is correct, the Core LMS Profile needs to be amended accordingly.

**Comment by jeremylangley** [comment]
As a LMS vendor, we do not currently allow the cancel a check-out/delete a loan natively within our application. Therefore we would suggest that this is left out of the Core LMS profile. A LMS vendor may choose to allow this if they natively support the functionality.

**Comment by franciscave** [comment]
Thanks for this useful clarification. 

I think we should review what is said in the REST Web Service Specification about cancellation of both check-out and check-in. It perhaps needs to be made clear that implementation of the check-out and check-in functions does not imply that cancellation also has to be implemented.

But in that case I wonder whether deleting a Patron record should be in the Core Profile. I can see that being able to delete a Reservation record makes sense, but should a terminal application user, typically a library patron, be allowed to delete their Patron record?

**Comment by jeremylangley** [comment]
Regarding reservations and being able to 'delete' a reservation record, while users would not be able to delete the entire record, but they may wise to cancel a reservation that they no longer require, along the same lines that they may want to edit a pick up location or suspend it until a future date. Therefore this may sit better under modifying a reservation - as this would be standard native library OPAC functionality. 

Similarly for patrons, the concept of deletion does not necessary apply to all LMS platforms, rather a concept of archiving/resigning, where this would only be able to achieved based on having no active transactions or other business rules set by the library such as requirements under the Regulation of Investigatory Powers Act 2000. Then there is the concept of 'right to be forgotten' in a GDPR sense which takes this one step further.

**Comment by franciscave** [comment]
I think we are agreed that it should not be possible for a library patron to use a terminal to cancel a loan, since that would in theory allow the patron to cancel the loan without checking-in the item on loan. On that basis, I think that we're right not to have deletion of loan records in the core profile.

I also see no reason why a library patron should not be able to use a terminal to change the status of a reservation to "cancelled". There is a reservation status code for this ("03" in LCF code list RVS). On that basis I think that modification of a reservation record could be included in the core profile. But it needs to be made clear that, while the modify function must be supported, it would only be required that the implementation support modification of reservation status in order to mark it as cancelled.

A similar argument could be made about modifying a patron record, except that in this case there isn't a patron status code (LCF code list PNS) that conveys the meaning "account cancelled by patron" (assuming the library allows this). Code value "16" ("Account expired") comes closest, but not close enough, I feel.

**Comment by jeremylangley** [comment]
> A similar argument could be made about modifying a patron record, except that in this case there isn't a patron status code (LCF code list PNS) that conveys the meaning "account cancelled by patron" (assuming the library allows this). Code value "16" ("Account expired") comes closest, but not close enough, I feel.

I would expect that If a patron record had previously been 'cancelled', it should not be retrieved via LCF. Therefore a code in the PNS table would not be relevant. Our interpretation of 'account expired' would be a temporary expiry, based on a specific date set by the library, that may/may not be extended based on the libraries business rules.

**Comment by franciscave** [comment]
Good point about cancelled records not being retrievable. But I'm not sure where this leaves us, when a library's policy is to allow patrons to cancel their accounts via self-service. How should this be achieved? If requesting a modification of the patron status to '16' (account expired) is not correct for this situation, do we need a new status code that means 'patron has requested cancellation'? That would enable a patron to request a modification to their patron record to change the status to the new value. Would that work?

**Comment by jeremylangley** [comment]
Yes, that could work. But for example within our ILS/LMS, there is the ability to "requested cancellation" and "requested cancellation and permanently forget membership details" So we would need at least two status options.

**Comment by franciscave** [comment]
At the LCF Technical Panel meeting on 17 June it was agreed that the Core Profile should only require support of the functions for retrieving specific records and lists of records. Since there are no omissions of retrieval functions in the Core Profile, this issue can be closed without action. Modification of the Core Profile to exclude creation, modification and deletion functions, and discussion of which functions should be included in new profiles for record management by library staff and possibly by library patrons, should be continued under issue #266.

**Comment by anthonywhitford** [comment]
Removed milestone "Someday.Patch" as there is no intention to progress further under this issue. Any other work will be under #266.
