### ISSUE TITLE
Patron self-registration

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#281]
Patron self-registration was discussed at the PlugFest on 11 May 2021. See issue #266. Since a self-registration would have to be validated before the new patron were allowed any library access privileges, a new patron status code 'validation pending' is needed for use in the patron record being created by self-registration.

**Comment by mdovey** [comment]
Agreed at technical panel on the 3/11/2022 to add a "pending patron" status code

**Comment by franciscave** [comment]
I propose the following change to code list PNS:

### PNS Patron status condition type (based upon ANSI/NISO Z39.70)

  *Code ID*   |*Code value*   |*Definition*                                  |*Notes*
  ----------- |-------------- |--------------------------------------------- |-------------------------
  ...               | ...                  | ...                                                               | ...
  PNS16       |16                 |Account expired                                         |*Added in v1.0.1*
  PNS17       |17                 |Pending patron                                          |To support patron self-registration<br/>*Added in vx.x.0*

**Comment by franciscave** [comment]
See pull request #289.

**Comment by mdovey** [comment]
Solution agreed by Technical Panel to add status code for pending registration
