### ISSUE TITLE
Location and app authentication

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#282]
At the PlugFest on 11 May 2021 there was discussion about the need for additional authentication when a patron is using an app on their mobile phone. LCF already has device and patron authentication, but it was pointed out that an LMS would in many circumstances need to authenticate the software app being used on the user's device as well as the location in which it was being used. We need to work out how the necessary authentication tokens would be obtained and communicated in requests.

**Comment by franciscave** [comment]
At the Technical Panel meeting of 11 October 2022 Colin Parker agreed to research a possible use case for this issue.

**Comment by mdovey** [comment]
Agreed to closed this issue at the Technical Panel on the 6th December 2022. This can be re-opened should a user requirement/use case be submitted.
