### ISSUE TITLE
Secure self issue

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#283]
At the PlugFest on 11 May 2021 there was discussion about mechanisms for making patron check-out and check-in secure, by requiring the client to include a token in the request that has been provided by a separate device such as a bluetooth beacon. The requirements for secure self issue need to be fully researched.

**Comment by franciscave** [comment]
At the Technical Panel meeting of 11 October 2022 there were no volunteers to research this issue. Unless a volunteer comes forward before the next Technical Panel meeting, it is proposed to close this issue without action.

**Comment by mdovey** [comment]
Agreed to closed this issue at the Technical Panel on the 6th December 2022. This can be re-opened should a user requirement/use case be submitted.
