### ISSUE TITLE
Offline check-in

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#284]
At the PlugFest on 11 May 2021 it was suggested that, for offline check-in of an item to be possible, a terminal would need to be able to create a temporary new loan record (with status '08' checked in) without access to the LMS or to the original loan record for the item. This temporary loan record would be in the same format as a regular loan record, but would generally have more limited content, and would generally use the barcode to identify the item rather than the URI of the item record. If this feature is to be fully supported by LCF, a modified schema for this kind of loan entity and the characteristics of the offline check-in function would need to be specified.

**Comment by mdovey** [comment]
Agreed at the technical panel on the 22/3/2021, that this was out of scope for the LCF protocol. How, an LMS stores the offline check-in data is an implementation decision for the LMS.
