### ISSUE TITLE
Failing to download lcf-schema:jar:1.2.0 from nexus.

### ISSUE THREAD

**Issue by JglNut** [bic-org-uk/bic-lcf#287]
I'm trying to build the lcfserver (https://github.com/ceridwen-com/lcfserver) per the instructions.
I'm getting the following error:
[ERROR] Failed to execute goal on project lcfserver-model: Could not resolve dependencies for project com.ceridwen.lcf:lcfserver-model:jar:lcf_1.2.0_server_2.1: Could not find artifact org.bic.ns.lcf:lcf-schema:jar:1.2.0 in nexus (http://nexus/repository/public) -> [Help 1]
[
I'm using JAVA 11 as the compiler source and target. That's the only change I made to the project so far.
I'm using maven 3.8.1.

Thanks in advance

**Comment by mdovey** [comment]
I'll check that - however as a workaround try adding the following to the maven file to pull the required jar from my repository:

      <repositories>
        <repository>
          <snapshots>
            <enabled>false</enabled>
          </snapshots>
          <id>central</id>
          <name>libs-release</name>
          <url>https://artifactory.ceridwen.com/artifactory/libs-release</url>
        </repository>
        <repository>
          <snapshots />
          <id>snapshots</id>
          <name>libs-snapshot</name>
          <url>https://artifactory.ceridwen.com/artifactory/libs-snapshot</url>
        </repository>
      </repositories>

**Comment by mdovey** [comment]
Transfered issue to https://github.com/ceridwen-com/lcfserver/issues/6#issue-1595120815
