### ISSUE TITLE
Notify patron when attempting to borrow a previously borrowed title

### ISSUE THREAD

**Issue by colinparkeruk** [bic-org-uk/bic-lcf#292]
We are aware of one LMS that already provides this feature and one that proposes to add it.
The existing implementation uses the same model as for a checkout that will incur a fee, i.e. the initial checkout request (with an override flag set to false) fails and, if the patron elects to proceed, the request is sent again with the override flag set to true.

For this scenario, maybe a new query parameter (similar to charge-acknowledged) could be added together with something similar to charge-ref in the response. Might be an idea to make these additions generic rather than specific to this use case.

The implementation proposed by another LMS again alerts the patron after the initial checkout request but then expects a checkin request if the borrow isn't required.

**Comment by franciscave** [comment]
If we were to add a new query parameter similar to 'charge-acknowledged', such as 'confirm-repeat-borrowing', we would need to add a new code value to list RDN (Reason for inability to approve request) which would mean 'No repeat borrowing confirmation in request'.

**Comment by mdovey** [comment]
Resolved at the April 2023 Technical Panel as wrap up of changes in #84
