### ISSUE TITLE
Fines or Fees?

### ISSUE THREAD

**Issue by jonathanwithers** [bic-org-uk/bic-lcf#294]
This is more of a clarification rather than an issue. 
For the following elements in patron entity is there a definition of what is a 'fine' vs. 'fee' ?
E03D13	Number of items for which fees other than fines are due
E03D14	Number of items for which fines are due

**Comment by franciscave** [comment]
A definition as to which charge types are fees and which are fines has, to my knowledge, never been stated. If you look at list [CHT](https://github.com/bic-org-uk/bic-lcf/blob/develop/docs/LCF-CodeLists.md#CHT), the obvious charge type that I'd describe as a fine would be '04' (Overdue). Would any other charge types be considered to be a fine?

**Comment by jonathanwithers** [comment]
Thanks, agree with overdue charges as fines. Spydus LMS allows sites to configure a charge type as either a fine or fee type. Almost all sites configure overdues as fines and some class Lost Item, Lost Processing and Damage charges as fines as well.

**Comment by franciscave** [comment]
This issue was discussed at the Technical Panel meeting on 11 October. It was agreed that each LMS will have its own definition of which charges are fines and which are fees, and this matter is therefore out of scope for LCF.
