### ISSUE TITLE
Loan status when creating a new loan

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#311]
E05 Loan: E05D07 (Loan status, 1-n) - what should be supplied when creating a new Loan entity if there is no applicable value in LOS as the field is mandatory? The expectation is that when a new loan is created, the initial code value would be ‘01’ (LOS01), i.e. ‘on loan to patron’. However, are there any circumstances in which a loan is created, other than when an item is checked out by a patron?

**Comment by nickilake** [comment]
In SirsiDynix Symphony, loans can be used to apply a current location (status) to items.  Common examples would be to set items to a MISSING or WITHDRAWN status though any status of the library’s choice could be applied in this way.

There is a closed list of 11 statuses under code list LOS (LOS01-LOS11).  What is expected in the scenario where a loan status in the ILS does not match one of the list entries?   There could be a number of custom statuses not easily covered by the current list.  What options do we have to expand on the list without interfering with future needs?

**Comment by mdovey** [comment]
For interoperability, we decided that these lists should be closed rather than open, and that the library system should map internal status into an appropriate one on the list. 

Where there is a clear requirement for additions to the list to accommodate a status not currently allowed for, please open an issue to request additional status codes.

@nickilake in the case of missing, withdrawn, etc. these are handled in LCF as a property of the Item entity (E02D11) using the CIS codelist (https://bic-org-uk.github.io/bic-lcf/LCF-CodeLists.html#CIS).

In terms of the original issue as regards creating a new Loan item, the review panel agreed to create a new status of Pending to be consistent with reservtions (see issue #312)
