### ISSUE TITLE
Reservation status when creating a new reservation

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#312]
E06 Reservation: E06D11 (Reservation status, 1-n) - What should be supplied when creating a new Reservation entity. RVS01 (Item available - in hold queue) seems ambiguous: does this mean that the item is queued (i.e. available to reserve but not yet available for collection), or does this mean that the item is available for collection? This possibly needs two separate codes, e.g. RVS01 hold placed, in queue, and RVSxx available to collect? Or is the assumption that the meaning of RVS01 needs to be interpreted based on the value of E06D15 (Position in hold queue)?

**Comment by jonathanwithers** [comment]
For Civica Spydus the E06D11 (Reservation status, 1-n) submitted in the create reservation request is not used as the status is assigned via subsequent workflow. A reservation that that has been allocated an item but is still in transit to it's pickup location is still assigned status RVS02.

**Comment by anthonywhitford** [comment]
At the point of creating a reservation, I suggest that it does not have a status, as the ILS/LMS has not yet accepted the request to create the reservation. This could be achieved through either (1) adding a "new" status to RVS; or (2) changing the cardinality to support the absence of this element in this scenario.

**Comment by mdovey** [comment]
The review panel agreed to add a new Pending status code to both this code list and also its equivalent in the Loan status code lists (see Issue #311).

@nickilake The CIS codelist (https://bic-org-uk.github.io/bic-lcf/LCF-CodeLists.html#CIS) used in the Circulation status of an Item entity  (E02D11), includes status CIS10 (In transit between library locations).
