### ISSUE TITLE
E01C27 in LCF-InformationEntityXMLBindings subfields have a numbering issue

### ISSUE THREAD

**Issue by anthonywhitford** [bic-org-uk/bic-lcf#329]
Within the LCF-InformationEntityXMLBindings.md, the entity E01C27 contains two subfields which are numbered as below:

![image](https://github.com/bic-org-uk/bic-lcf/assets/6545701/0814408d-6f9a-4fb0-96bd-00b5c85fca39)

The fields E01DXX.1 and E01DXX.02 should be numbered inline with the E01C27 complex field number.

**Comment by franciscave** [comment]
I have approved the change.
