### ISSUE TITLE
LCF-InformationEntityXMLBinding examples contain deprecated "version"

### ISSUE THREAD

**Issue by anthonywhitford** [bic-org-uk/bic-lcf#331]
In LCF version 1.0.1 we deprecated the "version" attribute within the primary entity responses. However, the examples within the InformationEntityXMLBinding documentation still often contain the version="1.0" attribute in the XML. 

eg. 
![image](https://github.com/bic-org-uk/bic-lcf/assets/6545701/e4a2abcd-93e5-465e-9a93-e614225ee623)

![image](https://github.com/bic-org-uk/bic-lcf/assets/6545701/bee8ee9e-53c8-4736-854a-67bf550a7119)

These version="1.0" should be removed from the examples.

**Comment by franciscave** [comment]
Oops! Agreed!
