### ISSUE TITLE
Previous releases v1.1.0 and v1.2.0 of LCF are no longer accessible via the GitHub repository Wiki

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#335]
It appears that the Wiki pages for v1.1.0 and v1.2.0 both link to the published v1.3.0 documentation, but they should in fact link to the v1.1.0 and v1.2.0 code branches. This only appears to affect the Documentation links.

I suspect this was a cut-and-paste error in preparing the release pages for versions 1.2.0 and 1.3.0.

**Comment by anthonywhitford** [comment]
I have reviewed this and it is an artifact from using GitHub Pages for the current LIVE release documentation. Once we push a new live version, the references for the historic versions need to be repointed back to the release tag against the historical branch.

**Comment by anthonywhitford** [comment]
I've updated the Release Documentation links for 1.2.0 and 1.1.0. The older versions were already correct.
