### ISSUE TITLE
Should descriptions of LCF functions include details of consequential entity/record updates?

### ISSUE THREAD

**Issue by franciscave** [bic-org-uk/bic-lcf#77]
The LCF Version 1.0.1 specification currently gives considerable detail of what entities are affected by a specific function such as check-out. Although the main result is the creation of a Loan entity/record, the status of the checked-out Item changes, as do several Patron properties, and there may be a need to create a Charge on the Patron's account. Should LCF document these consequential updates? When the new function 31 (Apply charge to Patron account) was added, there was some discussion about whether or not to describe the consequential updates, with Anthony suggesting that they weren't needed. I was not convinced, and retained a description of the consequential updates in the revision of the specification.

Anthony's argument is that the precise consequences of a particular action will vary according to circumstances, which makes it dangerous to try to specify them, because it then isn't clear whether LCF supports the circumstances that have not been specified. My view is that, while I can see the dangers, it is difficult to be clear about what we mean by "check-out" unless we describe the inevitable and most likely consequences.

Maybe there is a middle ground on this. We may be able to agree that describing consequences is helpful to make clear the full purpose of an LCF function, but that we need to be clear that these are by way of example and not definitive. We could include some generic wording such as:

"The use of this function may involve consequential updates to other records in the LCF implementation that are affected by the action being taken, in addition to those described here".

Any thoughts?

**Comment by mdovey** [comment]
Overall consensus at Technical Panel and Review Group is that this is not needed. However, the documentation in the dataframework on check-out needs revising (see issue #227)

**Comment by anthonywhitford** [comment]
Removing the milestone "someday.minor" as there is no further work expected on this issue.
