### ISSUE TITLE
Patron Name

### ISSUE THREAD

**Issue by Neil-IMIL** [bic-org-uk/bic-lcf#80]
Although E03 PATRON Entity E03D22 Name as a string is in line with SIP2 AE does this accurately reflect how systems store Patron Names and the best way to present and share this information?

**Comment by mdovey** [comment]
In most of the use cases for LCF, name is used for showback to the end user, so the library system can format the internal structure into a string in an appropriate way.

Obviously this doesn't work well for scenarios where LCF is being used to update or create a Patron record.

Instead of attempting to come up with our own structure for names (as SIP v3 attempted), we thought it might be better to adopt an existing standard such as vCard. This is the motivation for the enhancement outlined in issue #17 

However, #17 is currently down-prioritised to someday as to date there's been very little demand for this.

I'm going to close this in preference to #17 but if you have a pressing need or requirement for structured names, please add to #17 and we can reprioritise.

**Comment by mdovey** [comment]
After discussion at the review group - re-opening this to consider alternative approaches to solving this other than vcard (see issue #17)

**Comment by franciscave** [comment]
I was asked to provide a description of how personal names are handled in a structured way in ONIX.

The documentation of how authors' names can be expressed in ONIX, see elements P.7.11 - P.7.18 in the ONIX for Books Format Specification, which can be downloaded in HTML format from [here](https://www.editeur.org/files/ONIX%203/ONIX_for_Books_Release3-0_html_Best_Practice+codes_Issue_46_v1-5-3.zip) (it's in a ZIP file).

There are eight components of a structured name in ONIX. They are:

1. TitleBeforeNames

Qualifications and/or titles preceding a person’s names, eg ‘Professor’ or ‘HRH Prince’ or ‘Saint’. Optional and non-repeating: see Group P.7 introductory text for valid options.

2. NamesBeforeKey

Name(s) and/or initial(s) preceding a person’s key name(s), eg 'James J.' Optional and non-repeating.

3. PrefixToKey

A prefix which precedes the key name(s) but which is not to be treated as part of the key name, eg ‘van’ in Ludwig van Beethoven. This element may also be used for titles that appear after given names and before key names, eg ‘Lord’ in Alfred, Lord Tennyson. Optional and non-repeating.

4. KeyNames 

Key name(s), ie the name elements normally used to open an entry in an alphabetical list, eg ‘Smith’ or ‘Garcia Marquez’ or ‘Madonna’ or ‘Francis de Sales’ (in Saint Francis de Sales). Non-repeating. Required.

5. NamesAfterKey

Name suffix, or name(s) following a person’s key name(s), eg ‘Ibrahim’ (in Anwar Ibrahim). Optional and non-repeating.

6. SuffixToKey

A suffix following a person’s key name(s), eg ‘Jr’ or ‘III’. Optional and non-repeating.

7. LettersAfterNames

Qualifications and honors following a person’s names, eg ‘CBE FRS’. Optional and non-repeating.

8. TitlesAfterNames

Titles following a person’s names, eg ‘Duke of Edinburgh’. Optional and non-repeating.
The above descriptions are extracted from the ONIX specification. The model was developed almost 20 years ago. No-one has ever asked for any additional elements to be added. But I'm not sure how many ONIX users actually use these structured name elements.

**Comment by franciscave** [comment]
At the last Working Group meeting I was asked to find out about the level of usage of structured names by ONIX users. I've checked with EDItEUR. There are no stats on usage of structured names, but a significant proportion of ONIX records seen by EDItEUR contain all three versions of a personal contributor's name: PersonName; PersonNameInverted; and KeyNames in some combination with other structured name elements.

Graham Bell at EDItEUR has made some further points for our consideration.

1.   ONIX structured names work particularly well for names in cultures that tend to follow different naming conventions to the anglophone first name, middle names, family name convention, e.g. Chinese, Russian, Icelandic, Spanish and Arabic.
2.   Used properly, ONIX structured names are consistent with established library conventions such as AACR2 and RDA naming rules.
3.   ONIX has other elements that are used for contributor names, which we should consider if we're planning to introduce structured names for contributor names in the Manifestation entity, but could also be worth considering for corporate patron names. The elements in question are CorporateName and CorporateNameInverted. However, for corporate names there is no equivalent of the six structured name elements.
4.  ONIX uses the element UnnamedPerson with code list 19 for unnamed contributors. The code list allows differentiation between '01' (Unknown), '02' (Anonymous), '03' (et al), '04' (Various authors), '05' (Synthesised voice - male), '06' (Synthesised voice - female) and '07' (Synthesised voice - unspecified).
5.  In addition to a contributor's primary name, ONIX allows a contributor to have alternative names using the AlternativeName composite. The primary name _may_ and alternative names _must_ use code list 18 to specify different types of name, including '00' (Unspecified), '01' (Pseudonym), '02' (Authority-controlled name), '03' (Earlier name - used with AlternativeName only), '04' (Real name), '05' (Transliterated form of primary name - used with AlternativeName only), '06' (Later name - used with AlternativeName only).

**Comment by franciscave** [comment]
At the Technical Panel meeting on 19 March 2020 it was agreed to add structured personal names to the Patron entity only. If changes to the representation of names in Manifestation entities need to be considered, a separate issue should be opened.
