### ISSUE TITLE
Date range selection criteria

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#85]
This emerged in FASTEN discussions.

The ability to apply a date range as a SEL selection criteria e.g. to retrieve loans within a given date range (if used with SEL06 this could be used to return all current loans created in a given date range)

dateTimes field this might be applicable for include:

start-date
end-date
end-due-date
recall-notice-date
pickup-date
creation-date
payment-due-date
paid-date
payment-date

**Comment by franciscave** [comment]
Makes sense to me. I note that these selection criteria relate to several entities:

Loans: 
  -  start-date (E05D04) 
  -  end-date (E05D05) 
  -  end-due-date (E05D06) 
  -  recall-notice-date (E05D10)

Reservations: 
  -  start-date (E06D06)
  -  end-date (E06D10)
  -  pickup-date (E06D09)

Charges:
  -  creation-date (E07D10)
  -  payment-due-date (E07D11)
  -  paid-date (E07D16)

Payments:
  -  payment-date (E08D06)

One other date is supported by LCF include:

Patrons:
  -  patron-expiration-date (E03D30)

I'll add all the above to code list SEL.

**Comment by franciscave** [comment]
However... To support retrieving an entity instance list (function 02) by date range we need a way of expressing ranges, which hasn't been necessary with the existing set of code values in list SEL.

We can combine multiple selection criteria and LCF v1.0.1 says that these are ANDed together (see Q02C02). But we need a way of expressing binary relations ("equals" is currently implied): as a minimum, "less-than" and "greater-than". We could specify that any one of these may be used as a prefix in the Criterion value field (Q02D02.2), e.g. 'less-than YYYYMMDD'. Although introducing a new regular expression language is not ideal, this might be a more flexible approach than adding a new element 'Criterion relation' with code list containing 'equals', 'less-than', 'greater-than' and possibly other values.

**Comment by mdovey** [comment]
I would suggest that we use the syntax YYYYMMDD:YYYYMMDD to indicate a range so

20010101:20011231 would be the range (inclusive) 1/1/2001 - 31/12/2001

Then

:20011231 would be <= 31/12/2001
20010101 would be >= 1/1/2001

and

:  whilst valid would be a NOOP (basically means any date)

Also another character could be used instead of a :  (a - being a candidate)

**Comment by mdovey** [comment]
Part of the issue with this is that there might be an expectation for a repeated SEL criteria to be ORed rather than ANDed.

For instance 

?location-id=here&location-id=there 

might be used by someone expecting to get a list of items which are here or there, rather than the possibly empty list of things which are both here and there!

In the case of dates, someone might expect

?start-date=less-than 20000101&start-date=greater-than 20100101 

to return of list of things which started before 2000 and things which started after 2010 rather than the empty list of things each of which managed to start before 2000 and after 2010 i.e. a logical OR

where as

?start-date=greater-than 20000101&start-date=less-than 20100101 

would still be expected to be a logical AND (as a logical OR would return everything!)

I would suggest that

i) we insist the SEL criteria is not repeatable - both the two OR cases above can be done by multiple requests with the client doing the union of results (see below for an alternative)

ii) we use mathematical interval notation to denote ranges so

[a, b] means a <= x <= b
(a,b) means a < x < b
(a,b] means a < x <= b
[a,b) means a <= x < b

for open ended ranges we omit the relevant value, so

[,b] means x <= b ( alternatively (,b] means the same )
[,b) means x < b ( alternatively (,b) means the same )
[a,] means a <= x ( alternatively [a,) means the same )
(a,] means a < x ( alternatively (a,) means the same )

[,] (etc.) whilst valid means return everything, so is effectively a NOOP


P.S. if we really wanted to allow x < a OR b < x without requirement multiple requests we could do so by inverting the syntax i.e.

a),(b

if we really wanted to allow location-id=here OR location-id=there in a single request, we could use set notation i.e.

?location-id={here,there}

**Comment by franciscave** [comment]
The notation is going to need careful documenting, and I don't have time to do this right now. Do we need intervals for v1.0.1, or can we commit to adding it in v1.0.2?

In the meantime I'll add the new code values to list SEL.

**Comment by mdovey** [comment]
Superseded by issue #113

**Comment by franciscave** [comment]
"x < a OR x > b" could be described as a list of intervals. If we allow lists to contain intervals, this would increase the power of the grammar, e.g. we could then express "x < a OR b < x < c OR x = d":

    {(,a),(b,c),d}

We might find it hard to provide a clear use case for this, but it is a simple extension of what is proposed.

**Comment by mdovey** [comment]
OK, so the proposal is to used the following notations from ISO 31-11:1992 (https://en.wikipedia.org/wiki/ISO_31-11):

{...} to indicate a set of values (e.g. {value1, value2, value3} )
[...] to indicate a closed interval (e.g. [1,5] means 1<= x <= 5)
(...) to indicate an open interval (e.g. (1,5) means 1 < x < 5)

We permit:
half closed intervals (e.g. (1,5] or [1,5) )
unbounded intervals (e.g. (,5) to mean x < 5 )
intervals within lists (e.g. {(1,5), (10,15)} to mean 1 < x < 5 or 10 < x < 15 )

Intervals can be applied to any value which has a natural sort order e.g.

numbers (in ascending order)
dates (in ascending order)
strings (case insensitive alphabetical ascending order)

**Comment by franciscave** [comment]
I'm wondering where we should document this. It seems wrong to put this in the Data Framework, which should be syntax-neutral. So I think it should go in the REST specification. I suggest we add the following under function 02 Retrieve entity instance list:

#### Specifying ranges and sets in selection criteria *(added in v1.2.0)*

The following notation is derived from ISO 31-11:1992.

Where a selection criterion takes a date, date-time or a numerical value, a range may be specified using the following rules:

A range may be open, closed, half-closed or unbounded.

A closed range is specified by a pair of values, the first less (or earlier in time) than the second, separated by a comma and enclosed in square brackets, e.g. `[x,y]`, meaning that a value of `v` meets the selection criterion if it is the range `x <= v <= y`.

An open range is specified by a pair of values, the first less (or earlier in time) than the second, separated by a comma and enclosed in parentheses, e.g. `(x,y)`, meaning that a value of `v` meets the selection criterion if it is in the range `x < v < y`.

A half-closed range is specified by a pair of values, the first less (or earlier in time) than the second, separated by a comma and enclosed by a square bracket at the closed end of the range and by a parenthesis at the open end of the range, e.g. 

-    `(x,y]` means that a value `v` meets the selection criterion if it is is in the range `x < v <= y`
-    `[x,y)` means that a value `v` meets the selection criterion if it is in the range `x <= v < y`.

An unbounded range is an open, half-closed range in which at one open end of the range no bound is specified, e.g.:

-    `(,x)` means that a value `v` meets the selection criterion if it is in the range `v < x`
-    `(,x]` means that a value `v` meets the selection criterion if it is in the range `v <= x`
-    `(x,)` means that a value `v` meets the selection criterion if it is in the range `x < v`
-    `[x,)` means that a value `v` meets the selection criterion if it is in the range `x <= v`

A set of alternative values may be specified as a comma-separated list of values, ranges or a mixture of the two, enclosed in braces, e.g. 

-    `{a,b,c}` means that a value `v` meets the selection criterion if it is any of `a` or `b` or `c`
-    `{(x,y),z}` means that a value `v` meets the selection criterion if it is in the range `x < v < y` or is equal to `z`.
