### ISSUE TITLE
Generate XML Binding Documentation from XML Schema

### ISSUE THREAD

**Issue by mdovey** [bic-org-uk/bic-lcf#97]
Add xs:annotation to all elements in the XML Schema (currently only recent codelists and some elements are documented within the XML Schema)

Create XSLT to generate codelist and xml binding documentation from the XML Schema

**Comment by anthonywhitford** [comment]
Removing milestone "someday.minor" as there is no further work planned for this Closed issue.

**Comment by anthonywhitford** [comment]
Code list annotations were added under issue #316
